.TH USAGE: "1" "November 2011" "Usage: viptables command [rule]" "User Commands"
.SH NAME
Usage: \- Usage of viptables
.SH SYNOPSIS
.B viptables
\fIcommand \fR[\fIrule\fR]
.SH DESCRIPTION
.SS "Commands :"
.TP
\fB\-\-append\fR      \fB\-A\fR
Append rule
.TP
\fB\-\-insert\fR      \fB\-I\fR <n>
Insert rule before rule <n>
.TP
\fB\-\-list\fR        \fB\-L\fR
List rules
.TP
\fB\-\-delete\fR      \fB\-D[\fR<n>]
Delete rule <n> or the following rule
.TP
\fB\-\-flush\fR       \fB\-F\fR
Flush rules
.TP
\fB\-\-help\fR        \fB\-h\fR
Help
.SS "Rule options:"
.TP
\fB\-\-dom\-in\fR      \fB\-d\fR <n>
Client domid
.TP
\fB\-\-dom\-out\fR     \fB\-e\fR <n>
Server domid
.TP
\fB\-\-port\-in\fR     \fB\-p\fR <n>
Client port
.TP
\fB\-\-port\-out\fR    \fB\-q\fR <n>
Server port
.TP
\fB\-\-jump\fR        \fB\-j\fR {ACCEPT|REJECT}
What to do
.SS "Commands :"
.TP
\fB\-\-append\fR      \fB\-A\fR
Append rule
.TP
\fB\-\-insert\fR      \fB\-I\fR <n>
Insert rule before rule <n>
.TP
\fB\-\-list\fR        \fB\-L\fR
List rules
.TP
\fB\-\-delete\fR      \fB\-D[\fR<n>]
Delete rule <n> or the following rule
.TP
\fB\-\-flush\fR       \fB\-F\fR
Flush rules
.TP
\fB\-\-help\fR        \fB\-h\fR
Help
.SS "Rule options:"
.TP
\fB\-\-dom\-in\fR      \fB\-d\fR <n>
Client domid
.TP
\fB\-\-dom\-out\fR     \fB\-e\fR <n>
Server domid
.TP
\fB\-\-port\-in\fR     \fB\-p\fR <n>
Client port
.TP
\fB\-\-port\-out\fR    \fB\-q\fR <n>
Server port
.TP
\fB\-\-jump\fR        \fB\-j\fR {ACCEPT|REJECT}
What to do
