.TH USAGE: "1" "November 2011" "Usage: libv4v-config [OPTIONS] [LIBRARIES]" "User Commands"
.SH NAME
Usage: \- Usage of libv4v-config
.SH SYNOPSIS
.B libv4v-config
[\fIOPTIONS\fR] [\fILIBRARIES\fR]
.SH OPTIONS
.IP
[\-\-prefix[=DIR]]
[\-\-exec\-prefix[=DIR]]
[\-\-version]
[\-\-libs]
[\-\-cflags]
.IP
[\-\-prefix[=DIR]]
[\-\-exec\-prefix[=DIR]]
[\-\-version]
[\-\-libs]
[\-\-cflags]
